### ISSUE TITLE
Updating a mmrm object - a discussion

### ISSUE THREAD

**Issue by Generalized** [openpharma/mmrm#376] opened 2023-11-28 11:04 UTC
Let's say I have some model defined like this (don't mind the meaning, just an example)

```{r}
mmrm(formula = FVCPostDiff ~ Timepoint + us(Timepoint | PatientId), 
    data = data, control = mmrm_control(method = df, vcov = vcov_type))
```
where `df` and `vcov_type` are provided via parameters (e.g. function arguments or selected from some scenario list).

Now, let's assume I want to calculate the Cook's distance over the residuals.
I need to set the model estimation to `reml=FALSE`
Or assume I want to add some term or remove some term from the model - same story.

The modification happens outside the original context (=environment) where the model was fit, usually in another function.

```{r}
> update(m_mmrm, reml=FALSE)

Error in isTRUE(lhs) : object 'vcov_type' not found
Error in mmrm_control(method = df, vcov = vcov_type) :
Assertion on 'method' failed: Must be of type 'character', not 'closure'.
```
It couldn't find the df and vcov_type.
/ stats::df() is an existing functions, so it reported such strange kind of error. /

This can be fixed manually when fitting the model:
```{r}
# get the original call referring to external variables:

(orig_call <- paste(deparse(m_mmrm$call), collapse = ""))
[1] "mmrm(formula = FVCPostDiff ~ Timepoint + us(Timepoint | PatientId),     data = data, control = mmrm_control(method = df, vcov = vcov_type))"

# replace these references with actual values. Remember to quote them.

( new_call  <- stringr::str_replace_all(orig_call, c("df" = shQuote(df), "vcov_type" = shQuote(vcov_type))) )
[1] "mmrm(formula = FVCPostDiff ~ Timepoint + us(Timepoint | PatientId),     data = data, control = mmrm_control(method = \"Satterthwaite\", vcov = \"Asymptotic\"))"

# replace the original call
  m_mmrm$call <- str2lang(new_call)

# check

> m_mmrm$call
mmrm(formula = FVCPostDiff ~ Timepoint + us(Timepoint | PatientId), 
    data = data, control = mmrm_control(method = "Satterthwaite", 
        vcov = "Asymptotic"))
```

Good, let's try it now:

```
> update(m_mmrm, reml=FALSE)
Error in rep(1, nrow(data)) : invalid 'times' argument
```

OK, also "data" is not reachable outside the original context. (the message comes from the fact that data() is an existing R function)

Let's try more explicitly, as luckily data is stored in the mmrm object:
```{r}
> update(m_mmrm, reml=FALSE, data = m_mmrm$data)

mmrm fit

Formula:     FVCPostDiff ~ Timepoint + us(Timepoint | PatientId)
Data:        m_mmrm$data (used 91 observations from 44 subjects with maximum 3 timepoints)
Covariance:  unstructured (6 variance parameters)
Inference:   ML
Deviance:    64.11789

Coefficients: 
     (Intercept) TimepointWeek 16 TimepointWeek 56 
      0.05516954       0.09454553       0.10813262 

Model Inference Optimization:
Converged with code 0 and message: convergence: rel_reduction_of_f <= factr*epsmch
```

At last! So maybe try this way from the beginning?

OK, let's restart from the original case:
```{r}
> update(m_mmrm, reml=FALSE, data = m_mmrm$data)
Error in mmrm_control(method = df, vcov = vcov_type) :
Assertion on 'method' failed: Must be of type 'character', not 'closure'.
```
Let's add "df" and "vcov_type"
```{r}
> update(m_mmrm, reml=FALSE, data = m_mmrm$data, control = mmrm_control(method = m_mmrm$method, vcov = m_mmrm$vcov))
mmrm fit

Formula:     FVCPostDiff ~ Timepoint + us(Timepoint | PatientId)
Data:        m_mmrm$data (used 91 observations from 44 subjects with maximum 3 timepoints)
Covariance:  unstructured (6 variance parameters)
Inference:   ML
Deviance:    64.11789

Coefficients: 
     (Intercept) TimepointWeek 16 TimepointWeek 56 
      0.05516954       0.09454553       0.10813262 

Model Inference Optimization:
Converged with code 0 and message: convergence: rel_reduction_of_f <= factr*epsmch
```
OK, now it all works.

Would you consider adding `update.mmrm()` function which internally cares about these details, extracts the necessary slots and puts them into relevant places?

**Comment by danielinteractive** [comment] 2023-11-30 09:15
Thanks @Generalized , definitely worth looking into this. Can you please add some dummy definitions / code to your example so that it is reproducible so I can run this on my machine?

**Comment by danielinteractive** [comment] 2023-12-11 10:42
Thanks again @Generalized for the discussion and the example! I have looked into this now in detail. 

While it is tempting to try to come up with some kind of automated solution for your case, I don't think this is easy, sustainable or standard: 
- The problem is that we would need to infer which arguments are not available in the current scope, but should be taken instead from the model object itself. 
- This would modify the default behavior and lead to downstream problems. Hence I don't think this is sustainable.
- Also, I think also for other packages or general model fitting calls in R you will face the same situation. Which is fortunately easy to resolve, with relatively readable error messages from R, and with the knowledge you have as developer about what should be taken from the model object. Consider e.g. `glmmTMB` with a similar example, that behaves in the same way:

```r
library(glmmTMB)

glmm_datasets <- list(
  ds1 = Salamanders,
  ds2 = Salamanders
)
fit_glmm <- function(ds, fam = poisson) {
  glmmTMB(count ~ mined + (1|site), data=ds, family = fam)
}
glmm_models <- lapply(glmm_datasets, fit_glmm)
lapply(glmm_models, \(m) m$call)

do_something_with_glmm_model1 <- function(model) {
  update(model, se = FALSE)
}
do_something_with_glmm_model2 <- function(model) {
  update(model, se = FALSE, family = model$modelInfo$family)
}
do_something_with_glmm_model3 <- function(model) {
  update(model, se = FALSE, family = model$modelInfo$family, data = model$frame)
}

do_something_with_glmm_model1(glmm_models[[1]]) # fails
do_something_with_glmm_model2(glmm_models[[1]]) # fails
do_something_with_glmm_model3(glmm_models[[1]]) # works
```

Therefore I would propose to close this issue. Thanks again, and I think this discussion and workaround will be helpful in the future for others!

**Closed** 2024-01-02 11:10 UTC
Labels: enhancement
