### ISSUE TITLE
Address warnings and notes (as much as possible) from `R CMD check`

### ISSUE THREAD

**Issue by dinakar29** [openpharma/mmrm#76] opened 2022-07-22 13:50 UTC
On enableR:
The following notes and warnings are generated when `R CMD check` is run against this package.

```
* checking compilation flags used ... NOTE
Compilation used the following non-portable flag(s):
  ‘-Werror=format-security’ ‘-Wp,-D_FORTIFY_SOURCE=2’
  ‘-Wp,-D_GLIBCXX_ASSERTIONS’
* checking compiled code ... WARNING
File ‘mmrm/libs/mmrm.so’:
  Found ‘abort’, possibly from ‘abort’ (C)
    Objects: ‘mmrm.o’, ‘test-covariance.o’, ‘test-runner.o’,
      ‘test-utils.o’, ‘tmb.o’
  Found ‘printf’, possibly from ‘printf’ (C)
    Objects: ‘mmrm.o’, ‘test-covariance.o’, ‘test-runner.o’,
      ‘test-utils.o’, ‘tmb.o’
File ‘mmrm/libs/mmrm.so’:
  Found no calls to: ‘R_registerRoutines’, ‘R_useDynamicSymbols’

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs.
It is good practice to register native routines and to disable symbol
search.

See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
```
To do:
- [x] be able to reproduce this - on enableR?...
- [x] fix it if possible
  - [x] it is not clear where the non-portable flags come from. Possibly from TMB. However this warning does not show up without CRAN flag or on R 4.2 so should be ok.
  - [x] it is not clear where the `abort` and `printf` symbols come from. I checked the C++ code and we don't have any of this or similar. Maximum we have is `Rf_error` which is standard R interface for an error so cannot be the problem. Note that this warning does not occur on R 4.2

On Daniel's Macbook with `R CMD check --as-cran` on the built package tarball:

```
* checking compiled code ... NOTE
Datei ‘mmrm/libs/mmrm.so’:
  Found no calls to: ‘R_registerRoutines’, ‘R_useDynamicSymbols’

It is good practice to register native routines and to disable symbol
search.

See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
```
To do: 
- [x] See https://stackoverflow.com/questions/42313373/r-cmd-check-note-found-no-calls-to-r-registerroutines-r-usedynamicsymbols how to fix this.
- [x] fix it
- [x] ongoing work, as it is more complicated than initially thought:
	- [x] see https://github.com/kaskr/adcomp/blob/00046bb67271fa3db266cabd5bd815b58fa0045d/TMB/inst/include/tmb_core.hpp
	- [x] see https://github.com/glmmTMB/glmmTMB/blob/master/glmmTMB/src/init.h

Moreover parallel processes are not allowed in CRAN:
```
 ✖ | 2      47 | fit [0.7s]                                                      
  ────────────────────────────────────────────────────────────────────────────────
  Error (test-fit.R:175:3): mmrm falls back to other optimizers if default does not work
  Error in `.check_ncores(cores)`: 3 simultaneous processes spawned
  Backtrace:
    1. testthat::expect_silent(mmrm(formula, data_small))
         at test-fit.R:175:2
    9. mmrm::mmrm(formula, data_small)
   10. mmrm::refit_multiple_optimizers(fit, n_cores = n_cores, accept_singular = accept_singular)
   13. parallel::mclapply(...)
   14. parallel:::.check_ncores(cores)
  
  Error (test-fit.R:185:3): mmrm fails if no optimizer works
  Error in `.check_ncores(cores)`: 3 simultaneous processes spawned
  Backtrace:
    1. testthat::expect_error(...)
         at test-fit.R:185:2
    7. mmrm::mmrm(formula, data_small, reml = FALSE)
    8. mmrm::refit_multiple_optimizers(fit, n_cores = n_cores, accept_singular = accept_singular)
   11. parallel::mclapply(...)
   12. parallel:::.check_ncores(cores)
  ────────────────────────────────────────────────────────────────────────────────
```
To do:
- [x] disable parallel processing in the 2 tests

**Comment by danielinteractive** [comment] 2022-07-23 13:43
@dinakar29 thanks for this, unfortunately I cannot reproduce the warning you get for the compiled code on my local machine. Is it possible for me to reproduce this myself on enableR? What are the steps for that? (Only then I can try to change something to fix it)

**Comment by danielinteractive** [comment] 2022-07-24 14:27
@dgkf fyi - we have been diligent here trying to fix check results as much as possible, but on our internal R 4.0.4 server there might still be a message, which originates outside of the `mmrm` package code it seems, and is not shown during checks on R 4.2.

**Comment by dgkf-roche** [comment] 2022-07-24 20:30
Thanks @danielinteractive - I've seen this in other compiled packages and it seems to be raised in error. If you do see anything problematic about this warning that would be reason to be concerned, we'd appreciate your input - you have more background with packaging C code than I do. 

I think this is a benign warning just due to the system (C compiler differences perhaps?). Even if it is problematic, as far as I can tell, the worst possible outcome would be that the process is terminated, which might be frustrating for users, but is rather unlikely to produce any erroneous results. That said, we haven't seen it actually abort in our exploration so far.

**Comment by danielinteractive** [comment] 2022-07-25 07:10
Thanks a lot @dgkf-roche , that is good to hear. I also think it is a false positive warning in this case and I guess it could even be a bug in `R CMD check` itself that has been fixed in more recent R versions.

I am further working now on fixing the relevant warning about the registration of Call routines.

**Comment by dgkf** [comment] 2022-07-25 14:39
If there's a way to register the routines that doesn't require acrobatics around TMB, that's awesome. If not, then it's a tradeoff between trying to appease `R CMD check` and wanting to use more widely accepted tools as they were intended. This is similar to building models with `rstan`, where the generated code produces a few known `R CMD check` notes. 

In either case, I think there's value in staying consistent with other TMB tools, even if that comes with some `R CMD check` flags. I don't see a problem with that if there's good justification for it.

**Comment by danielinteractive** [comment] 2022-07-25 15:19
Thanks @dgkf - so I took the code now more or less from `glmmTMB` in the pull request here and it looks relatively concise, and what is important depends on `TMB` to define the names for the Call routines to register. It would be awesome if you could review that. (No problem if you don't have time, just let me know)

**Closed** 2022-07-26 12:02 UTC
Labels: SP3, priority, devops
